[package]
name = "microphone_service_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.13"
tokio = { version = "1", features = ["full"] }
bytemuck = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"