version: "3.7"
services:
  power_prophet_frontend:
    container_name: power_prophet_frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - power_prophet_frontend_network

networks:
  power_prophet_frontend_network:
    driver: bridge
