version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
