import os

MINIO_ENDPOINT = os.environ["MINIO_ENDPOINT"]
MINIO_ACCESS_KEY = os.environ["MINIO_ACCESS_KEY"]
MINIO_SECRET_KEY = os.environ["MINIO_SECRET_KEY"]
BUCKET_NAME = os.environ["BUCKET_NAME"]

MONGODB_HOST = os.environ["MONGODB_HOST"]
MONGODB_PORT = int(os.environ["MONGODB_PORT"])

SINGLE_MEASURE_MODEL_URL = os.environ["SINGLE_MODEL_URL"]
EXPERT_MODEL_URL = os.environ["EXPERT_MODEL_URL"]
DATA_SERVICE_URL = os.environ["DATA_SERVICE_URL"]

TEST_DEVICE = "1000kV荆潇Ⅰ线高抗C相"


# SINGLE_MEASURE_MODEL_URL = "http://192.168.4.117:48011"
# EXPERT_MODEL_URL = "http://192.168.4.117:48012"
# DATA_SERVICE_URL = "http://192.168.4.117:8002"
